# https://www.quora.com/What-is-the-difference-between-NumPy-and-Pandas


In [1]:
import numpy as np
a1=np.array([1,2,3,4,5])


In [2]:
print(a1)

[1 2 3 4 5]


In [3]:
print(type(a1))

<class 'numpy.ndarray'>


In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [6]:
np.random.rand(5,3)

array([[0.77511057, 0.34080299, 0.82261098],
       [0.46678787, 0.43343789, 0.65364665],
       [0.5608086 , 0.7165902 , 0.95276896],
       [0.09182695, 0.66735088, 0.03905649],
       [0.92135719, 0.73905584, 0.96275928]])

In [7]:
import pandas as pd
s1=pd.Series([1,2,3,4])

In [8]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [9]:
dictionary={'a':1,'b':2,'c':3,'d':4,'e':5}

In [10]:
sd=pd.Series(dictionary)

In [11]:
sd

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [12]:
#Program to create ndarray series
Data=[[2,3,4],[5,6,7]]

In [13]:
Data

[[2, 3, 4], [5, 6, 7]]

In [14]:
#Program to create Data Frame with two dictionaries
dict1={'a':1,'b':2,'c':3,'d':4} #Define Dictionary 1
dict2={'a':5,'b':6,'c':7,'d':8} #Define Dictionary 1

In [15]:
Data={'first':dict1,'second':dict2} #Define Data with dict1 and dict2
df=pd.DataFrame(Data)#create a DataFrame

In [16]:
df

first  second
a      1       5
b      2       6
c      3       7
d      4       8

# Class

In [18]:
class ComplexNumber:
    def __init__(self,r = 0,i = 0):
        self.real = r
        self.imag = i

    def getData(self):
        print("{0}+{1}j".format(self.real,self.imag))

In [19]:
c1=ComplexNumber(2,3)

In [21]:
c1.getData

<bound method ComplexNumber.getData of <__main__.ComplexNumber object at 0x0000011D3C6DFDD8>>

In [ ]:
https://www.w3schools.com/python/python_classes.asp